# atlantis.yaml
  repos:
  - id: /.*/
    branch: /.*/
    workflow: default
    apply_requirements: [ mergeable]
    allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
    allowed_workflows: []
    allow_custom_workflows: true
      #    repo_config_file: atlantis-test.yaml
  workflows:
    default:
      plan:
        steps:
        - run: echo "In Terraform Init and Plan updated"
        - run: terragrunt init
        - run: terragrunt plan
      apply:
        steps:
        - run: terragrunt apply -auto-approve