# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "tf-atlantis-state-demo"
    encrypt = true
    key     = "atlantis_instance/terraform.tfstate"
    region  = "ap-south-1"
  }
}
